### ISSUE TITLE
from_pylist and from_pydict is failing with python 3.9.21 and getadft 0.4.

### ISSUE THREAD

**Issue by nekulkarni** [Eventual-Inc/Daft#3879]
### Describe the bug

On Python 3.9.21, when using python venv on a Mac host, from_pydict or from_pylist throws an error:
<details>

(ray_venv_3.9.21) neerakul@6c7e67c3dc48 ray_venv_3.9.21 % python3 --version
Python 3.9.21
(ray_venv_3.9.21) neerakul@6c7e67c3dc48 ray_venv_3.9.21 % python3
Python 3.9.21 (main, Feb 28 2025, 14:33:19)
[Clang 16.0.0 (clang-1600.0.26.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import daft
>>> daft.__version__
'0.4.5'
>>> df = daft.from_pydict({"a": [1, 2, 3], "b": ["a", "b", "c"]})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/api_annotations.py", line 39, in _wrap
    return timed_func(*args, **kwargs)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/analytics.py", line 225, in tracked_fn
    result = fn(*args, **kwargs)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/convert.py", line 80, in from_pydict
    return DataFrame._from_pydict(data)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/dataframe/dataframe.py", line 540, in _from_pydict
    data_micropartition = MicroPartition.from_pydict(data)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/recordbatch/micropartition.py", line 108, in from_pydict
    table = RecordBatch.from_pydict(data)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/recordbatch/recordbatch.py", line 135, in from_pydict
    series = item_to_series(k, v)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/series.py", line 652, in item_to_series
    series = Series.from_pylist(item, name)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/series.py", line 88, in from_pylist
    if data and isinstance(data[0], np.datetime64):
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/lazy_import.py", line 56, in __getattr__
    raise e
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/lazy_import.py", line 53, in __getattr__
    return getattr(self._load_module(), name)
AttributeError: 'NoneType' object has no attribute 'datetime64'
</details>
### To Reproduce

Steps:
```sh
> pyenv install -v 3.9
> ~/.pyenv/versions/3.9.21/bin/python -m venv ray_venv_3.9.21
> cd ray_venv_3.9.21
> source bin/activate
> pip install getdaft==0.4.5
> python --version 
Python 3.9.21
```

```python
>>> import daft
>>> daft.__version__
'0.4.5'
>>> df = daft.from_pydict({"a": [1, 2, 3], "b": ["a", "b", "c"]})
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/api_annotations.py", line 39, in _wrap
    return timed_func(*args, **kwargs)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/analytics.py", line 225, in tracked_fn
    result = fn(*args, **kwargs)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/convert.py", line 80, in from_pydict
    return DataFrame._from_pydict(data)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/dataframe/dataframe.py", line 540, in _from_pydict
    data_micropartition = MicroPartition.from_pydict(data)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/recordbatch/micropartition.py", line 108, in from_pydict
    table = RecordBatch.from_pydict(data)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/recordbatch/recordbatch.py", line 135, in from_pydict
    series = item_to_series(k, v)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/series.py", line 652, in item_to_series
    series = Series.from_pylist(item, name)
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/series.py", line 88, in from_pylist
    if data and isinstance(data[0], np.datetime64):
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/lazy_import.py", line 56, in __getattr__
    raise e
  File "/Users/neerakul/Documents/ray_expt/ray_venv_3.9.21/lib/python3.9/site-packages/daft/lazy_import.py", line 53, in __getattr__
    return getattr(self._load_module(), name)
AttributeError: 'NoneType' object has no attribute 'datetime64'
```
### Expected behavior

from_pydict or from_pylist should just work. I have taken the above sample line of code from https://www.getdaft.io/projects/docs/en/stable/api_docs/doc_gen/expression_methods/daft.struct.html#daft.struct.

### Component(s)

Other

**Comment by universalmind303** [comment]
Confirmed that this is a bug introduced in 0.4.5. 

same code works fine in `0.4.4`. Will look in to tracing what introduced the bug
### 0.4.4
```py
Python 3.12.7 (main, Oct 16 2024, 07:12:08) [Clang 18.1.8 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import daft
>>> daft.__version__
'0.4.4'
>>> df = daft.from_pydict({"a": [1,2,3], "b": ["a","b","c"]})
>>>
```

**Comment by colin-ho** [comment]
https://github.com/Eventual-Inc/Daft/pull/3829/files#diff-330d5cb02da70c01dd0de195f645cd9688b568205b177ea89e75c99ca557880eR88 @rchowell It's cuz we try lazy import numpy.

But numpy is not a dependency of Daft. When we lazy import and its not there it returns None

**Comment by colin-ho** [comment]
> https://github.com/Eventual-Inc/Daft/pull/3829/files#diff-330d5cb02da70c01dd0de195f645cd9688b568205b177ea89e75c99ca557880eR88 [@rchowell](https://github.com/rchowell) It's cuz we try lazy import numpy.
> 
> But numpy is not a dependency of Daft. When we lazy import and its not there it returns None

I think we should:
1. `if data and isinstance(data[0], np.datetime64):` add a check here that numpy is imported
2. Give some warning when we try lazy import and it's not there

**Comment by universalmind303** [comment]
@nekulkarni as a workaround for 0.4.5, you can just install `numpy` and things should work as expected.

**Comment by rchowell** [comment]
ack. thanks colin!
