### ISSUE TITLE
Daft doesn't work with Deltalake v1.0: cannot import name '_convert_pa_schema_to_delta' from 'deltalake.schema'

### ISSUE THREAD

**Issue by mwc360** [Eventual-Inc/Daft#4677]
### Describe the bug

Daft fails on an import error when using Deltalake v1.0:

File ~/jupyter-env/python3.11/lib/python3.11/site-packages/daft/dataframe/dataframe.py:1011, in DataFrame.write_deltalake(self, table, partition_cols, mode, schema_mode, name, description, configuration, custom_metadata, dynamo_table_name, allow_unsafe_rename, io_config)
   1009 import deltalake
   1010 import pyarrow as pa
-> 1011 from deltalake.schema import _convert_pa_schema_to_delta
   1012 from deltalake.writer import AddAction, try_get_deltatable, write_deltalake_pyarrow
   1013 from packaging.version import parse

ImportError: cannot import name '_convert_pa_schema_to_delta' from 'deltalake.schema' (/home/trusted-service-user/jupyter-env/python3.11/lib/python3.11/site-packages/deltalake/schema.py)

### To Reproduce

table_df =daft.read_parquet(
            'abfss://......./'
)
table_df.write_deltalake(
    'abfss://.........',
    mode="overwrite"
)

### Component(s)

Other

**Comment by rohitkulshreshtha** [comment]
Looks like `_convert_pa_schema_to_delta` was removed 

https://github.com/delta-io/delta-rs/commit/92e75bb21703bdb8c14fcd2479e3cce0cd9f64f8#diff-23bbc9f2c12503c99cf19596ba2e9c6fb7d77f398e6b974323d11151bf53521f

**Comment by rohitkulshreshtha** [comment]
Related: 
https://github.com/Eventual-Inc/Daft/issues/2457
