### ISSUE TITLE
Read/Write Lance files on S3 error in ray mode

### ISSUE THREAD

**Issue by plotor** [Eventual-Inc/Daft#4216]
### Describe the bug

The version of datf I'm using is 0.4.10, and i found that when the version of `pylance` is lower than 0.14.0, executing the `write_lance` to write to S3 will result in an error:

```text
Traceback (most recent call last):
  File "/opt/workspace/github/ray-examples/daft/daft_lance.py", line 45, in <module>
    df.write_lance(uri="s3://zhenchao-dev/daft/lance", io_config=io_config)
  File "/opt/workspace/github/ray-examples/.venv/lib/python3.12/site-packages/daft/api_annotations.py", line 26, in _wrap
    return timed_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/workspace/github/ray-examples/.venv/lib/python3.12/site-packages/daft/analytics.py", line 199, in tracked_method
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/workspace/github/ray-examples/.venv/lib/python3.12/site-packages/daft/dataframe/dataframe.py", line 1256, in write_lance
    dataset = lance.LanceDataset.commit(table_uri, operation, read_version=version, storage_options=storage_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LanceDataset.commit() got an unexpected keyword argument 'storage_options'
```

After I upgraded the `pylance` version to 0.15.0, I was able to successfully use `write_lance`. However, there is still an error when using `read_lance`:

```text
Traceback (most recent call last):

  ...
  
  File "/opt/workspace/github/ray-examples/.venv/lib/python3.12/site-packages/ray/_private/serialization.py", line 556, in serialize
    return self._serialize_to_msgpack(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/workspace/github/ray-examples/.venv/lib/python3.12/site-packages/ray/_private/serialization.py", line 534, in _serialize_to_msgpack
    pickle5_serialized_object = self._serialize_to_pickle5(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/workspace/github/ray-examples/.venv/lib/python3.12/site-packages/ray/_private/serialization.py", line 481, in _serialize_to_pickle5
    raise e
  File "/opt/workspace/github/ray-examples/.venv/lib/python3.12/site-packages/ray/_private/serialization.py", line 476, in _serialize_to_pickle5
    inband = pickle.dumps(
             ^^^^^^^^^^^^^
  File "/opt/workspace/github/ray-examples/.venv/lib/python3.12/site-packages/ray/cloudpickle/cloudpickle.py", line 1479, in dumps
    cp.dump(obj)
  File "/opt/workspace/github/ray-examples/.venv/lib/python3.12/site-packages/ray/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
           ^^^^^^^^^^^^^^^^^
RuntimeError: Failed to serialize: ValueError: LanceError(IO): Generic S3 error: Bucket 'zhenchao-dev' not found, /Users/runner/work/lance/lance/rust/lance-io/src/object_store.rs:229:13
```

### Component(s)

Ray Runner

**Comment by colin-ho** [comment]
Does it work after your fix: https://github.com/Eventual-Inc/Daft/pull/4214?

**Comment by plotor** [comment]
> Does it work after your fix: [#4214](https://github.com/Eventual-Inc/Daft/pull/4214)?

Yes, I will find time to fix this issue in #4214 this week.

**Comment by rchowell** [comment]
Hey @plotor thanks for the PR, have you confirmed the bucket exists when doing the read? Just want to ensure we identify if the root cause in on daft's side for this specific read error in the issue description.

> Generic S3 error: Bucket 'zhenchao-dev' not found

**Comment by plotor** [comment]
> Hey [@plotor](https://github.com/plotor) thanks for the PR, have you confirmed the bucket exists when doing the read? Just want to ensure we identify if the root cause in on daft's side for this specific read error in the issue description.
> 
> > Generic S3 error: Bucket 'zhenchao-dev' not found

Yes, I have already confirmed that the bucket `zhenchao-dev` exists. After analysis, the reasons for the error are from two aspects:

1. The current minimum version requirement of `pylance` is too old (the latest version is 0.25). I have tested multiple versions of `pylance` and found that the `pylance` version needs to be upgraded to at least 0.20.0
2. We are using an object storage that is compatible with the `s3://` protocol (not AWS S3), which requires access in the Virtual Host Style mode. However, the `force_virtual_addressing` parameter of S3Config has not been passed through to the Lance SDK.

**Comment by colin-ho** [comment]
Closed with https://github.com/Eventual-Inc/Daft/pull/4214
